#!/bin/sh
# Toggle one of the optional page stylesheets (gruvbox, font).
# config.py skips <name>.css while the flag file disabled-<name> exists.
flag="$QUTE_CONFIG_DIR/disabled-$1"
if [ -e "$flag" ]; then
    rm "$flag"
    state=on
else
    touch "$flag"
    state=off
fi
echo "config-source" >> "$QUTE_FIFO"
echo "message-info '$1 stylesheet $state'" >> "$QUTE_FIFO"
